.PHONY: all
all: time1 time2 time3 time4

time1: time1.o
	clang time1.o -o time1

time1.o: time1.c
	clang -c time1.c

time2: time2.o
	clang time2.o -o time2

time2.o: time2.c
	clang -c time2.c

time3: time3.o
	clang time3.o -o time3

time3.o: time3.c
	clang -c time3.c

time4: time4.o
	clang time4.o -o time4

time4.o: time4.c
	clang -c -O0 time4.c
