.PHONY: all
all: fopen1 fopen2 shift1 shift2

fopen1: fopen1.c
	clang fopen1.c -o fopen1

fopen2: fopen2.c
	clang fopen2.c -o fopen2

shift1: shift1.c
	clang shift1.c -o shift1

shift2: shift2.c
	clang shift2.c -o shift2
